import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F8FAFC' },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
  },
  loadingText: { marginTop: 12, fontSize: 16, color: '#6B7280' },
  searchContainer: {
    padding: 16,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  searchBar: { backgroundColor: '#F9FAFB', elevation: 0, shadowOpacity: 0 },
  listContainer: { flex: 1, padding: 16 },
  emptyState: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 60,
  },
  emptyStateTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#374151',
    marginTop: 12,
    marginBottom: 8,
  },
  emptyStateText: {
    fontSize: 14,
    color: '#6B7280',
    textAlign: 'center',
    lineHeight: 20,
  },
  vehicleCard: {
    marginBottom: 12,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
  },
  cardContent: {
    paddingVertical: 12,
  },
  vehicleHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  vehicleInfo: { flexDirection: 'row', alignItems: 'center', flex: 1 },
  vehicleIcon: { margin: 0, marginRight: 12 },
  vehicleTextContainer: { flex: 1 },
  registrationNo: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#1F2937',
    marginBottom: 4,
  },
  statusContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  statusIcon: { margin: 0, marginRight: 4 },
  statusText: { fontSize: 14, fontWeight: '500' },
  lastValidated: { fontSize: 12, color: '#6B7280', marginTop: 2 },
  validateButton: {
    backgroundColor: '#007AFF',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 8,
    minWidth: 100,
    minHeight: 36,
    justifyContent: 'center',
  },
  submittedButton: { backgroundColor: '#10B981' },
  validatingButton: { backgroundColor: '#F59E0B' },
  errorButton: { backgroundColor: '#EF4444' },
  buttonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonIcon: { margin: 0, marginRight: 4 },
  validateButtonText: {
    color: '#fff',
    fontWeight: '600',
    fontSize: 12,
  },
  messageContainer: {
    padding: 8,
    borderRadius: 6,
    marginTop: 8,
  },
  successMessage: { backgroundColor: '#D1FAE5' },
  errorMessage: { backgroundColor: '#FEE2E2' },
  infoMessage: { backgroundColor: '#DBEAFE' },
  messageText: {
    fontSize: 12,
    lineHeight: 16,
  },
  successMessageText: { color: '#065F46' },
  errorMessageText: { color: '#991B1B' },
  infoMessageText: { color: '#1E40AF' },
  footer: {
    padding: 16,
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
  },
  statsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  statItem: { alignItems: 'center' },
  statNumber: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#1F2937',
    marginBottom: 4,
  },
  statLabel: { fontSize: 12, color: '#6B7280' },
  statDivider: { width: 1, height: 30, backgroundColor: '#E5E7EB' },
});
